---
title: "p8105_hw5_dry2115"
author: "Dayoung Yu"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

library(tidyverse)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```


### Problem 1

Read in and clean _Washington Post_ homicide data.

```{r}
homicide_df = 
  read_csv("data/homicide-data.csv", na = c("", "NA", "Unknown")) %>%
  mutate(
    city_state = str_c(city, state, sep = ", "),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unresolved",
      disposition == "Open/No arrest"        ~ "unresolved",
      disposition == "Closed by arrest"      ~ "resolved"),
    victim_race = case_when(
      victim_race == "White" ~ "white",
      victim_race != "White" ~ "non-white"),
    victim_age = as.numeric(victim_age)
    ) %>%
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")))
```


glm for baltimore

```{r}
baltimore_df = homicide_df %>%
  filter(city == "Baltimore") %>%
  mutate(resolved = as.numeric(resolution == "resolved")) %>%
  select(resolved, victim_age, victim_sex, victim_race)

baltimore_glm = baltimore_df %>%
  glm(resolved ~ victim_age + victim_sex + victim_race, data = ., family = binomial())

baltimore_glm %>% 
  broom::tidy() %>%
  mutate(OR = exp(estimate)) %>%
         #(CI = confint(baltimore_glm))

  filter(term == "victim_racewhite") %>%
  mutate(term = str_replace(term, "white", ": White")) %>%
  knitr::kable(digits = 3)

```


glm for each city

```{r}
city_glm = homicide_df %>%
  mutate(resolved = as.numeric(resolution == "resolved")) %>%
  group_by(city_state) %>%
  nest() %>%
  mutate(models = map(data, ~glm(resolved ~ victim_age + victim_sex + victim_race, data = ., family = binomial())),
         models = map(models, broom::tidy)) %>%
  select(-data) %>%
  unnest()

city_glm %>%
  select(city_state, term, estimate) %>%
  mutate(term = fct_inorder(term)) %>%
  spread(key = term, value = estimate) %>%
  mutate(race_OR = exp(victim_racewhite)) %>%
  select(city_state, race_OR) %>%
  knitr::kable(digits = 3)

```

plot of ORs and CIs for each city

```{r}

```

